### ISSUE TITLE
background transparency

### ISSUE THREAD

**Issue by ChengLuffy** [yvbbrjdr/pipesocks#12]
Because the background is transparent, and there is no blur, in some situations it is difficult to see the text.

**Comment by yvbbrjdr** [comment]
This issue only happens under linux and Windows. Under macOS, if you set the background color to transparent, the foreground (texts of labels, text fields, buttons, etc) will remain opaque and everything is normal. However, under other systems, the background will keep overlapping itself. It is possible that under linux and Windows, Qt tries to constantly take screenshots and print it on the background of the window, but the screenshot includes the application window itself, causing the problem. So I used setOpacity under linux and Windows to avoid this problem, making all the elements on the window transparent, and it is not possible to set background blur in Qt. I'll try to fix it, otherwise I'll let the window opaque under linux and Windows. (Or I will be too lazy to do this.)

**Comment by yvbbrjdr** [comment]
At last, I would like to disable transparency under linux and Windows. Are you satisfied?
