### ISSUE TITLE
使用汤不热的时候自动断开

### ISSUE THREAD

**Issue by nzcool** [yvbbrjdr/pipesocks#24]
试过多次，看汤不热上的视频，大概十秒钟，就自动断开。

**Comment by yvbbrjdr** [comment]
Are you using pipesocks for Desktop or iOS?

**Comment by nzcool** [comment]
iOS 10.3

**Comment by yvbbrjdr** [comment]
It's a known issue that when playing videos (especially high-quality videos, 1080p60fps, 1440p, etc), pipesocks will be killed by iOS due to overuse of CPU when rendering these videos and that [NEKit](https://github.com/zhuhaow/NEKit) is claiming so many threads. This bug is unsolvable until [libnekit](https://github.com/zhuhaow/libnekit) is released. However, it's not a problem if you watch lower-quality videos (I have tested 1080p and it works well).

By the way, if you want to report a bug for pipesocks-iOS, don't file it here. This project is pipesocks for Desktop and the Desktop version doesn't have this issue. Instead, you should go [here](https://github.com/pipesocks/pipesocks-iOS).
